/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./game/GameMgr"
import Hammer from "./game/Hammer"
import Mouse from "./game/Mouse"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=960;
    static height:number=640;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="GameScene.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/GameMgr.ts",GameMgr);
        reg("game/Hammer.ts",Hammer);
        reg("game/Mouse.ts",Mouse);
    }
}
GameConfig.init();